DROP TABLE IF EXISTS Enrollment;

DROP TABLE IF EXISTS User;

CREATE TABLE User (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS Course;

CREATE TABLE Course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(500)
);

CREATE TABLE Enrollment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT,
  course_id BIGINT,
  date TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT fk_user_enrollment FOREIGN KEY (user_id) REFERENCES User,
  CONSTRAINT fk_course_enrollment FOREIGN KEY (course_id) REFERENCES Course
);
